# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'GHLogDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for GHLogDemo

  pod 'GHLog', :path => '../../GHLog'
  pod 'GHLog/iPhone', :path => '../../GHLog'
  pod 'GHLog/iPad', :path => '../../GHLog'
  pod 'GHLog/iWatch', :path => '../../GHLog'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
    end
  end
end


